// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieaoekmqnuwawfzhdece.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYW9la21xbnV3YXdmemhkZWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzODc5ODcsImV4cCI6MjA5MDk2Mzk4N30.417bAB9O2sE_KDxwvoflLU-rRwQTR4BAz6hJ0Os2d2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});